describe('Validate User', () => {
  beforeEach(() => {
    cy.visit('http://172.22.104.250/login')
    cy.get('input:first').clear().type('useradminclient1')
    cy.get('input:last').clear().type('Aa123456!')
    cy.get(':nth-child(4) > .md-button > .md-ripple > .md-button-content').click()
  })
  const useride = 'prbcypress10'

  it('Create User', () => {
    cy.get(':nth-child(10) > .sidebar-menu-item').click()
    cy.get(':nth-child(10) > div > .nav > :nth-child(2) > .nav-link > .sidebar-normal').click()
    cy.get('[data-vv-as="usuario"]').clear().type(useride)
    cy.get('[data-vv-name="first_name"]').clear().type('prb')
    cy.get('[data-vv-name="last_name"]').clear().type('cypress')
    cy.get('[data-vv-name="email"]').clear().type('echavezp@tigo.com.gt')
    cy.get('[data-vv-name="msisdn"]').clear().type('40008245')
    cy.get('[data-vv-name="role"]').first().click()
    cy.get(':nth-child(1) > .md-list-item-button > .md-list-item-content > .md-list-item-text').click()
    cy.get('[data-vv-name="password"]').clear().type('Aa123456!')
    cy.get('[data-vv-name="confirmPassword"]').clear().type('Aa123456!')
    // cy.get('.md-inline-checkboxes.md-size-15 > .md-checkbox > .md-checkbox-container').click()
    // cy.get('.md-size-20 > .md-checkbox > .md-checkbox-container').click()
    cy.get('.md-success > .md-ripple > .md-button-content').click()
    cy.screenshot()
    cy.contains('.alert > span', 'Se creó el usuario exitosamente')
    cy.url().should('include', '/backoffice/users')
  })

  it('User List', () => {
    cy.get(':nth-child(10) > .sidebar-menu-item').click()
    cy.get(':nth-child(10) > div > .nav > :nth-child(1) > .nav-link > .sidebar-normal').click()
    cy.url().should('include', '/backoffice/users')
    cy.wait(500)
    cy.screenshot()
  })

  it('User Serch', () => {
    cy.get(':nth-child(10) > .sidebar-menu-item').click()
    cy.get(':nth-child(10) > div > .nav > :nth-child(1) > .nav-link > .sidebar-normal').click()
    cy.get('[type="search"]').clear().type(useride + '{enter}')
    cy.wait(500)
    cy.url().should('include', '/backoffice/users')
    cy.screenshot()
  })

  it('View User', () => {
    cy.get(':nth-child(10) > .sidebar-menu-item').click()
    cy.get(':nth-child(10) > div > .nav > :nth-child(1) > .nav-link > .sidebar-normal').click()
    cy.get('[type="search"]').clear().type(useride + '{enter}')
    cy.wait(500)
    cy.get(':nth-child(1) > :nth-child(4) > .md-table-cell-container > .md-success > .md-ripple > .md-button-content > .md-icon').click()
    cy.url().should('include', '/backoffice/vusers')
    cy.wait(800)
    cy.screenshot()
  })

  it('Edit User', () => {
    cy.get(':nth-child(10) > .sidebar-menu-item').click()
    cy.get(':nth-child(10) > div > .nav > :nth-child(1) > .nav-link > .sidebar-normal').click()
    cy.get('[type="search"]').clear().type(useride + '{enter}')
    cy.wait(500)
    cy.get(':nth-child(1) > :nth-child(4) > .md-table-cell-container > .md-warning > .md-ripple > .md-button-content > .md-icon').click()
    cy.wait(500)
    cy.get('.md-success > .md-ripple').click()
    cy.contains('.alert > span', 'Se actualizó el usuario exitosamente')
    cy.screenshot()
  })

  it('Delete User', () => {
    cy.get(':nth-child(10) > .sidebar-menu-item').click()
    cy.get(':nth-child(10) > div > .nav > :nth-child(1) > .nav-link > .sidebar-normal').click()
    cy.get('[type="search"]').clear().type(useride + '{enter}')
    cy.wait(500)
    cy.get(':nth-child(1) > :nth-child(4) > .md-table-cell-container > .md-danger > .md-ripple > .md-button-content > .md-icon').click()
    cy.get('.swal2-confirm').click()
    // cy.get('.swal2-cancel').click()
    cy.screenshot()
    cy.contains('.alert > span', 'Registro eliminado existosamente')
    cy.url().should('include', '/backoffice/users')
  })
})
